//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPCRMatEng.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PCRMatEngEntities : DbContext
    {
        public PCRMatEngEntities()
            : base("name=PCRMatEngEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TD_Files> TD_Files { get; set; }
        public DbSet<TD_PCR> TD_PCR { get; set; }
        public DbSet<TD_Transaction> TD_Transaction { get; set; }
        public DbSet<TM_Action> TM_Action { get; set; }
        public DbSet<TM_GroupCode> TM_GroupCode { get; set; }
        public DbSet<TM_Level> TM_Level { get; set; }
        public DbSet<TM_Purpose> TM_Purpose { get; set; }
        public DbSet<TM_Status> TM_Status { get; set; }
        public DbSet<TM_Supervisor> TM_Supervisor { get; set; }
        public DbSet<TM_User> TM_User { get; set; }
        public DbSet<TM_UserType> TM_UserType { get; set; }
        public DbSet<V_Detail_Current> V_Detail_Current { get; set; }
        public DbSet<V_Supervisor> V_Supervisor { get; set; }
        public DbSet<V_Transaction> V_Transaction { get; set; }
        public DbSet<V_User_Info> V_User_Info { get; set; }
        public DbSet<V_Max_Round> V_Max_Round { get; set; }
        public DbSet<V_Tran> V_Tran { get; set; }
    }
}
