//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPCRMatEng.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_Files
    {
        public string group_code { get; set; }
        public string year { get; set; }
        public int run_no { get; set; }
        public string file_name { get; set; }
        public string path { get; set; }
        public string upload_by { get; set; }
        public System.DateTime upload_dt { get; set; }
        public Nullable<System.DateTime> delete_dt { get; set; }
    
        public virtual TD_PCR TD_PCR { get; set; }
    }
}
