//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPCRMatEng.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_PCR
    {
        public TD_PCR()
        {
            this.TD_Files = new HashSet<TD_Files>();
            this.TD_Transaction = new HashSet<TD_Transaction>();
        }
    
        public string group_code { get; set; }
        public string year { get; set; }
        public int run_no { get; set; }
        public string compounditem { get; set; }
        public string compounditem_file { get; set; }
        public string line { get; set; }
        public byte purpose_id { get; set; }
        public string change_content { get; set; }
        public string reason { get; set; }
        public string ipqc_rank { get; set; }
        public string ipqc_compound { get; set; }
        public Nullable<System.DateTime> imp_dt { get; set; }
        public string start_batch { get; set; }
        public string ipqc_file { get; set; }
        public string start_compound { get; set; }
        public string start_compound_file { get; set; }
    
        public virtual ICollection<TD_Files> TD_Files { get; set; }
        public virtual TM_GroupCode TM_GroupCode { get; set; }
        public virtual TM_Purpose TM_Purpose { get; set; }
        public virtual ICollection<TD_Transaction> TD_Transaction { get; set; }
    }
}
