//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPCRMatEng.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM_Supervisor
    {
        public string emp_code { get; set; }
        public int group_id { get; set; }
        public System.DateTime update_dt { get; set; }
        public string update_by { get; set; }
        public bool email_flag { get; set; }
    }
}
