//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPCRMatEng.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Max_Round
    {
        public string group_code { get; set; }
        public string year { get; set; }
        public int run_no { get; set; }
        public Nullable<byte> round1 { get; set; }
        public byte status_id { get; set; }
        public byte lv_id { get; set; }
    }
}
