//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPCRMatEng.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Tran
    {
        public string pcr_no { get; set; }
        public string group_code { get; set; }
        public string year { get; set; }
        public int run_no { get; set; }
        public string status_name { get; set; }
        public string lv_name { get; set; }
        public string purpose_name { get; set; }
        public string action_name { get; set; }
        public byte purpose_id { get; set; }
        public byte status_id { get; set; }
        public byte lv_id { get; set; }
        public byte action_id { get; set; }
        public string actor { get; set; }
        public System.DateTime act_dt { get; set; }
        public string change_content { get; set; }
        public string reason { get; set; }
        public bool active { get; set; }
        public int org_id { get; set; }
        public int group_id { get; set; }
        public string ipqc_rank { get; set; }
        public string compounditem { get; set; }
        public string line { get; set; }
        public Nullable<System.DateTime> imp_dt { get; set; }
        public string start_batch { get; set; }
        public string start_compound { get; set; }
    }
}
